# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PHP-Functions-Mail
version:      0.04
version_from: lib/PHP/Functions/Mail.pm
installdirs:  site
requires:
    Jcode:                         0
    Net::SMTP:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
